
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 09 19:18:56 CST 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PyC = 6;
  public static final int Digito = 4;
  public static final int Tilde = 16;
  public static final int Simbolo = 21;
  public static final int ComillaDoble = 19;
  public static final int Coma = 17;
  public static final int Separador = 7;
  public static final int LlaveC = 10;
  public static final int LlaveA = 3;
  public static final int Cadena = 22;
  public static final int EOF = 0;
  public static final int ComillaSimple = 18;
  public static final int Ast = 13;
  public static final int CONJ = 2;
  public static final int Positiva = 14;
  public static final int Id = 20;
  public static final int error = 1;
  public static final int Flecha = 8;
  public static final int Conc = 11;
  public static final int Disy = 12;
  public static final int Letra = 5;
  public static final int Interro = 15;
  public static final int DosP = 9;
}

